name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'  # Replace with the version you're using

      # Step 3: Restore dependencies
      - name: Restore .NET dependencies
        run: |
          dotnet restore

      # Step 4: Build the project
      - name: Build the project
        run: |
          dotnet build --configuration Release

      # Step 5: Publish the iOS app
      - name: Publish iOS app
        run: |
          dotnet publish idiapoc.csproj -c Release -r ios -p:Platform=iPhone -p:BuildIpa=true -o ./output

      # Step 6: Upload the IPA file
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: YourApp.ipa
          path: ./output/*.ipa
